.rjob_settings:
  rjob_common: &rjob_common_variables
    CHARGED_GROUP: base_det

  rjob_two_gpu: &rjob_two_gpu_variables
    <<: *rjob_common_variables
    EXPECTED_CPU: 8
    EXPECTED_GPU: 2
    EXPECTED_MEMORY: 60000

  rjob_one_gpu: &rjob_one_gpu_variables
    <<: *rjob_common_variables
    EXPECTED_CPU: 8
    EXPECTED_GPU: 1
    EXPECTED_MEMORY: 60000

  rjob_cpu: &rjob_cpu_variables
    <<: *rjob_common_variables
    EXPECTED_CPU: 2
    EXPECTED_GPU: 0
    EXPECTED_MEMORY: 8192

stages:
  - lint


check-format:
  stage: lint
  tags:
    - rjob
  variables:
    <<: *rjob_cpu_variables
  only:
    - master
    - merge_requests
    - tags
  before_script:
    - pip3 install flake8
    - pip3 install isort==4.3.21
  script:
    - isort -rc basedet --diff
    - isort --check-only -rc basedet
    - isort --check-only -rc playground/examples
    - isort --check-only -rc tests
    - flake8 .
