.rjob_settings:
  rjob_common: &rjob_common_variables
    CHARGED_GROUP: base_det

  rjob_two_gpu: &rjob_two_gpu_variables
    <<: *rjob_common_variables
    EXPECTED_CPU: 8
    EXPECTED_GPU: 2
    EXPECTED_MEMORY: 60000

  rjob_one_gpu: &rjob_one_gpu_variables
    <<: *rjob_common_variables
    EXPECTED_CPU: 8
    EXPECTED_GPU: 1
    EXPECTED_MEMORY: 60000

  rjob_cpu: &rjob_cpu_variables
    <<: *rjob_common_variables
    EXPECTED_CPU: 2
    EXPECTED_GPU: 0
    EXPECTED_MEMORY: 8192

stages:
  - lint
  - unit-test


check-format:
  stage: lint
  tags:
    - rjob
  variables:
    <<: *rjob_cpu_variables
  only:
    - master
    - merge_requests
    - tags
  before_script:
    - pip3 install flake8
    - pip3 install isort==4.3.21
  script:
    - isort -rc basedet --diff
    - isort --check-only -rc basedet
    - isort --check-only -rc playground/examples
    - isort --check-only -rc tests
    - flake8 .


unit-test:
  stage: unit-test
  needs: ["check-format"]
  tags:
    - rjob-gpu
  variables:
    <<: *rjob_cpu_variables
  script:
    - pip3 install --upgrade setuptools
    - pip3 install megbrain==8.15.1
    - printf "$AWS_ACCESS_KEY_ID_\n$AWS_SECRET_ACCESS_KEY_\n\n\n" | aws configure
    - pip3 install -r requirements.txt --ignore-installed
    - pip3 install -e .
    - pip3 install -r requirements-dev.txt
    - pip3 install opencv_python==4.2.0.34  # to avoid import cv2 errror
    - python3 -m pytest tests --cov=basedet --junitxml=report.xml --cov-report=html --cov-report term
    - coverage xml
    - aws --endpoint-url=http://oss.i.brainpp.cn s3 sync htmlcov/ s3://basedet/coverage/htmlcov/
  artifacts:
    paths:
      - coverage.xml
      - report.xml
    reports:
      cobertura: coverage.xml
      junit: report.xml
  only:
    - master
    - merge_requests
    - tags
